; Listing generated by Microsoft (R) Optimizing Compiler Version 19.41.34120.0 

	TITLE	C:\Users\cyberqueenmeg\Desktop\itt-210\Topic 2\ConsoleApplication1.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_function
PUBLIC	_main
PUBLIC	_function2
; Function compile flags: /Odsp
_TEXT	SEGMENT
_main	PROC
; File C:\Users\cyberqueenmeg\Desktop\itt-210\Topic 2\ConsoleApplication1.c
; Line 6
	push	ebp
	mov	ebp, esp
; Line 7
	push	9
	call	_function
	pop	ecx
; Line 8
	push	2
	push	1
	call	_function2
	pop	ecx
	pop	ecx
; Line 9
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odsp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_function PROC
; File C:\Users\cyberqueenmeg\Desktop\itt-210\Topic 2\ConsoleApplication1.c
; Line 1
	push	ebp
	mov	ebp, esp
; Line 2
	mov	eax, DWORD PTR _a$[ebp]
	inc	eax
; Line 3
	pop	ebp
	ret	0
_function ENDP
_TEXT	ENDS
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12	; size = 4
_function2 PROC
; File C:\Users\cyberqueenmeg\Desktop\itt-210\Topic 2\ConsoleApplication1.c
; Line 1
	push	ebp
	mov	ebp, esp
; Line 2
	mov	eax, DWORD PTR _a$[ebp]
	mov ebx, DWORD PTR _b$[ebp]
	add eax, ebx
; Line 3
	pop	ebp
	ret	0
_function2 ENDP
_TEXT	ENDS
END
